init:
  - set QTDIR=C:\Qt\5.10.1\msvc2013_64
  - set PATH=%PATH%;%QTDIR%\bin;C:\Program Files (x86)\NSIS\bin
  - call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" amd64
install:
  - git submodule update --init --recursive
build_script:
  - echo namespace { const char* version = "%APPVEYOR_BUILD_VERSION%"; } > version.h
  - cd librabbitmq
  - qmake
  - nmake
  - cd ..
  - cd app
  - qmake
  - nmake
  - xcopy /y release\anno.exe ..\release\
  - cd ..
  - makensis anno-installer.nsi
artifacts:
  - path: anno-isto-installer-v*.exe
    name: anno-isto-installer
