init:
  - set QTDIR=C:\Qt\5.8\msvc2013_64
  - set PATH=%PATH%;%QTDIR%\bin;C:\Program Files (x86)\NSIS\bin
  - call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" amd64
install:
  - git submodule update --init --recursive
build_script:
  - echo namespace { const char* version = "%APPVEYOR_BUILD_VERSION%"; } > version.h
  - qmake anno.pro
  - nmake
  - makensis anno-installer.nsi
artifacts:
  - path: anno-installer-v*.exe
    name: anno-installer
